### ISSUE TITLE
Implement re-creation mechanism for ES indexes

### ISSUE THREAD

**Issue by BastianGem** [apiman/apiman#1024]
A mechanism is needed to recreate all ES indexes if the index mapping has changed after an update. 
In general we have at least 2 options for this:

1. Using the export/import mechanism from the UI
This should happen in the background so the user doesn't notice it.
2. Use the ES java api

**Comment by msavy** [comment]
One potential option would be just to use the Import-Export API (just on the server), to export the contents; drop the indexes; and then re-import:

I think that would work 🤔
    
* We pick up an environment variable or something to trigger it.
* Use the export function to save the data to some safe location -- so that if something goes horribly wrong it's recoverable from the file manually (e.g. if the server crashed or set on fire at an unfortunate moment).
* Drop all of the indexes.
* Recreate all indexes and reimport.

**Comment by volkflo** [comment]
We already had a mechanism before https://github.com/apiman/apiman/pull/743

**Comment by msavy** [comment]
Ah ok, I'll check that out.

**Comment by volkflo** [comment]
I think this was all deleted with ES7 migration

**Comment by msavy** [comment]
Plan is now to create a migration script to allow people to easily export from older versions of Apiman and enrich the JSON with any missing schema definitions, then they can re-import into the new version of Apiman (2.1).

This will probably be a standalone migrator application, but we could consider other ways of achieving this.

**Comment by msavy** [comment]
Just need to decide how we're going to package this and which bundles we ship it with.
