### ISSUE TITLE
SOAP gateway?

### ISSUE THREAD

**Issue by cen1** [apiman/apiman#204]
At the moment if you invoke a SOAP service through Apiman gateway the original WSDL is returned, together with original port address URLs which means you can freely invoke SOAP service bypassing Apiman completely after you get the initial WSDL. Am I doing something wrong or is SOAP not completely finished yet?

**Comment by EricWittmann** [comment]
No you're right - SOAP support isn't really finished yet.  The UI certainly implies that setting the endpoint type to SOAP will do something interesting, but it doesn't.

That said, in the latest version of apiman you can use the URL Rewriting policy to convert all the URLs in the WSDL to the appropriate apiman gateway endpoint format.

**Comment by cen1** [comment]
I will take a look at that, thanks.

**Comment by osbeorn** [comment]
I've been trying to use this policy to rewrite the <soap:address> URL to the Apiman gateway endpoint URL, but it seems that this isn't working. If I attach a debugger to Apiman I notice, that the code in URLRewritingStream.java doesn't find any URLs in the body of the response and therefore no replacements are made.

**Comment by osbeorn** [comment]
My guess is that this is a problem with content encoding, gzip in this case.

**Comment by osbeorn** [comment]
I was right. If i disable gzip encoding by sending Accept-Encoding=identity header, the URLs are correctly replaced.

**Comment by EricWittmann** [comment]
Ah ha!  Well that makes a lot of sense I think.  The question is, what to do about it...

I'm open to suggestions!

For awhile now we have wanted to create a GZIP policy, but the idea there was to GZIP the body so that back-end APIs didn't need to.  In other words, the back end API would just respond with JSON or XML, and then apiman would gzip it.  That wouldn't help in this case, obviously.

We could of course also have a policy that *unzips* the content.

Thoughts?

**Comment by EricWittmann** [comment]
For those who find their way to this issue, have a look at this JIRA:

https://issues.jboss.org/browse/APIMAN-1072

I am closing this ticket, because we track this sort of thing in JIRA instead of github.
