### ISSUE TITLE
Can't build with tests skip

### ISSUE THREAD

**Issue by cen1** [apiman/apiman#211]
I usually like to skip tests when building Apiman to save some time but there seems to be a problem with 1.1.7. With tests enabled it builds fine.

Command: mvn clean -Dmaven.test.skip=true install -Pinstall-all-wildfly8

Error:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:50 min
[INFO] Finished at: 2015-09-04T10:08:47+02:00
[INFO] Final Memory: 122M/642M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project apiman-gateway-test: Could not resolve
 dependencies for project io.apiman:apiman-gateway-test:jar:1.1.7.Final: Could n
ot find artifact io.apiman:apiman-gateway-platforms-vertx3:jar:tests:1.1.7.Final
 in nexus (redacted-local-nexus) -> [H
elp 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :apiman-gateway-test

**Comment by EricWittmann** [comment]
Yeah - there is a test-scope dependency between apiman-gateway-test and apiman-gateway-platforms-vertx3, as you discovered.  You have a couple of options.  First, once you do a full "mvn install" you should have that artifact in your local .m2.  Future maven builds can then skip the tests and it will still build (because even though io.apiman:apiman-gateway-platforms-vertx3:jar:tests will be missing from the reactor it will find it in .m2).

If you're feeling bold, you could probably contribute a fix for this.  I'm thinking that the io.apiman:apiman-gateway-platforms-vertx3:jar:tests dependency should only be added if tests are *not* being skipped.  So I think we might be able to isolate that dependency in a profile.  Something like this only in reverse:

http://stackoverflow.com/questions/15767132/how-do-i-skip-a-maven-plugin-execution-if-dskiptests-or-dmaven-test-skip-tr
