### ISSUE TITLE
Failed to load API definition

### ISSUE THREAD

**Issue by sbelondr** [apiman/apiman#2648]
### Apiman Version

3.1.3

### Apiman Manager Distro

WildFly

### Apiman Gateway Distro

Vert.x

### Java Version

**openjdk 11.0.21**

### Operating System

Debian 12

### Are you running Apiman in a container, or on an orchestration platform?

Docker Compose

### Describe the bug

Hi,
When I use the latest apiman (3.1.3), I have this issue with this url : http://apiman.local.gd:8080/apimanui/api-manager/def :
![Screenshot from 2024-08-29 09-52-39](https://github.com/user-attachments/assets/913c8fa8-d9aa-4921-b3c7-b6166e7fc4d4)

I don't have error with the `docker logs ` command

### How to Reproduce

Download the apiman-docker-compose-3.1.3.Final.zip archive and launch the following commands : 
```
docker-compose -f docker-compose.setup.yml up
docker-compose up -d
```

Go to the Apiman UI (http://apiman.local.gd:8080/apimanui/) and click to admin > REST API
![image](https://github.com/user-attachments/assets/0ae56e42-0240-4c08-ae69-a095b65a552c)

**Comment by msavy** [comment]
Thanks, Samuel.

This is already fixed in BPL's [Long-Term Supported Build for Apiman 3.x](https://www.blackparrotlabs.io). 

I will be rolling these fixes into the Apiman 4 release when we finally have time to finish it, which will be the next Apiman release in the upstream. Working hard on that, but I have no timelines to give you.

BPL funds all of the development of the Apiman project, and we need to have a viable business for Apiman to survive, hence why we provide LTS builds only to enterprise customers. I hope you understand.

I believe we already had discussions with your organisation in the past, so feel free to reach out any time via email or telephone.
