### ISSUE TITLE
The link to the API definition does not show for YAML definitions

### ISSUE THREAD

**Issue by owsega** [apiman/apiman#738]
The link to view the definition of an API does not show when the API definition was pasted in the Swagger (YAML) format.

The definition shows on the page where the API is being created/edited (e.g. http://localhost:8080/apimanui/api-manager/orgs/myOrg/apis/myApi/1.0/def  where `myOrg` is the organization and `myApi` is the API's name). 

This implies the definition is being stored.

However, when you visit the page where external clients/users can view the API (e.g. http://localhost:8080/apimanui/api-manager/browse/orgs/myOrg/myApi/1.0/), the "**View API Definition**" link does not show under the Version selectbox or anywhere else on the page.

**Comment by volkflo** [comment]
I figured out the problem, our UI differs from the original ui and we never did a PR for this problem. (We may just forgot it)

The problem is in https://github.com/apiman/apiman/blob/master/manager/ui/war/plugins/api-manager/ts/consumer/consumer-api.ts

In line 148 there is only a check for :
` if ($scope.version.definitionType == 'SwaggerJSON' && hasSwagger)`

You have to add 
`if (($scope.version.definitionType == 'SwaggerJSON' || $scope.version.definitionType == 'SwaggerYAML') && SwaggerUIBundle)`

This appears on other places too, you have to search for it :)

**Comment by bekihm** [comment]
@owsega: It would be very nice if you open the PR for this fix if this solution works. :-)

**Comment by owsega** [comment]
I will. I haven't been able to build the source out-of-the-box after pulling it. Once I am able to do that, and I test the solution, I will.
