### ISSUE TITLE
Is there any updated roadmap?

### ISSUE THREAD

**Issue by tevosouza** [apiman/apiman#801]
Hi guys!!!
I'm trying to contribute with this project, but i facing problems to find an updated roadmap or the product vision of this project. I've fixed some issue on one or two plugins and made some PRs that was very fast accepted (thanks @EricWittmann). 

I'm really interested in apiman project (it's challenging me to study APIs and improve my knowledge of java).

What is the next steps of this project, what can i do to contribute with it.

Thanks !

**Comment by EricWittmann** [comment]
Hi @tevosouza - the reality of Apiman is that it is mostly in long-term maintenance mode.  It still has some active users of course, which you can see from the PRs and whatnot.  However, it is not being actively pushed forward by its original sponsor (Red Hat).  This project was originally going to be the official Red Hat API Management solution until Red Hat acquired 3scale a couple of years ago.  At that point this project transitioned to becoming legacy.

I still maintain the project by helping with issues, answering questions, reviewing and merging PRs.  However, I no longer actively develop or drive the development of the project.

That said, it's possible that some of the active community members such as e.g. @volkflo have some ideas about desired changes that would provide opportunities for contribution.

**Comment by tevosouza** [comment]
Oh, i got it!
thanks a lot for your answer!!

**Comment by volkflo** [comment]
Hi @tevosouza and @EricWittmann 

Maybe this is a good point to explain who we are and what we plan to do with apiman in the future.

@bekihm  and I are working for the German [Scheer-Group](https://www.scheer-group.com/en/).
Our software platform [Scheer PAS](https://www.scheer-pas.com/en/) contains an [API Management](https://www.scheer-pas.com/en/api-management/) solution.
This API Management solution is based on the original apiman.

But we customized it to fit our needs and only deliver it as docker images.
You can view our default setup [here](https://doc.scheer-pas.com/display/INSTALLATION/API+Management+Installation+Guide#APIManagementInstallationGuide-OverviewontheDockerSetupofAPIManagement)

In the last year, we evaluated some other API Mgmt Solutions and decided to stay with apiman.
This means that we will also contribute our changes that are not specific to the apiman-project in the future.

The next time we are working on the following topics:

* Refactoring the REST API of th UI because it leaks a lot of sensitive data
* We plan to support Elasticsearch 7
  * With this we will also switch to Elasticsearch and Kibana provided by Amazons [OpenDistro](https://opendistro.github.io/for-elasticsearch/)
* Migration to Java 11

In the last months, we created a "Developer Portal" for apiman. Such a portal can be found in many other API Management Solutions.
With this, you are able to share the APIs (and their API-Key) with an external customer or end-user.
At the moment this is not open source.
![image](https://user-images.githubusercontent.com/13332383/73449117-c8075080-4362-11ea-903a-8db10da1ada5.png)

But there are also a lot of other problems that could be improved:
Some of the following points need refactoring to:

* The old UI should be ported into a new Angular based application
* The multiple storages are hard to support for us, because we only use elasticsearch
* The same applies for the different solutions with tomcat and wildfly (we are only using tomcat)
* The test framework

@tevosouza in general, we are happy about any contribution (or contribution to our roadmap).

Best wishes,
Florian

**Comment by bekihm** [comment]
@tevosouza Would be great if you decide to support the apiman project further. :-)

**Comment by tevosouza** [comment]
> Hi @tevosouza and @EricWittmann
> 
> Maybe this is a good point to explain who we are and what we plan to do with apiman in the future.
> 
> @bekihm and I are working for the German [Scheer-Group](https://www.scheer-group.com/en/).
> Our software platform [Scheer PAS](https://www.scheer-pas.com/en/) contains an [API Management](https://www.scheer-pas.com/en/api-management/) solution.
> This API Management solution is based on the original apiman.
> 
> But we customized it to fit our needs and only deliver it as docker images.
> You can view our default setup [here](https://doc.scheer-pas.com/display/INSTALLATION/API+Management+Installation+Guide#APIManagementInstallationGuide-OverviewontheDockerSetupofAPIManagement)
> 
> In the last year, we evaluated some other API Mgmt Solutions and decided to stay with apiman.
> This means that we will also contribute our changes that are not specific to the apiman-project in the future.
> 
> The next time we are working on the following topics:
> 
> * Refactoring the REST API of th UI because it leaks a lot of sensitive data
> * We plan to support Elasticsearch 7
>   
>   * With this we will also switch to Elasticsearch and Kibana provided by Amazons [OpenDistro](https://opendistro.github.io/for-elasticsearch/)
> * Migration to Java 11
> 
> In the last months, we created a "Developer Portal" for apiman. Such a portal can be found in many other API Management Solutions.
> With this, you are able to share the APIs (and their API-Key) with an external customer or end-user.
> At the moment this is not open source.
> ![image](https://user-images.githubusercontent.com/13332383/73449117-c8075080-4362-11ea-903a-8db10da1ada5.png)
> 
> But there are also a lot of other problems that could be improved:
> Some of the following points need refactoring to:
> 
> * The old UI should be ported into a new Angular based application
> * The multiple storages are hard to support for us, because we only use elasticsearch
> * The same applies for the different solutions with tomcat and wildfly (we are only using tomcat)
> * The test framework
> 
> @tevosouza in general, we are happy about any contribution (or contribution to our roadmap).
> 
> Best wishes,
> Florian

Woww!
Well, I'm working for Japanese group [Honda Logistics]https://www.honda-logistics.co.jp/ (Brazilian division) and we started to develop a new system for operations managements (upgrade legacy systems) and after evaluations of some solutions, I've decide to use apiman and customize to my needs if necessary.
By now, I'm working on some policies that we need (baby steps..hehe).
We plan to fall into apiman core as soon as possible and you give me a good point to start.
I really excited about this project.

I hope we can see good things for this project in the future

Thanks!!

**Comment by EricWittmann** [comment]
As part of this discussion I should add that, although Apiman is no longer Red Hat's API Management solution, we are always very supportive of open source projects.  We can continue maintaining this project as we are today (limited oversight/management by me) or, if the community grows and we decide it make sense, we could donate the project to a foundation (e.g. Eclipse, Apache, or Linux).  That has been discussed in the past and was obviously not done.

In any case, I guess I would want to assure everyone that Red Hat would never pull the rug out from under any open source project.

**Comment by msavy** [comment]
I intend to continue contributing where I can 👍
