### ISSUE TITLE
Setting up development environment

### ISSUE THREAD

**Issue by tevosouza** [apiman/apiman#820]
Hi guys!
How I said before, I'm not a java developer (yet), on my work we use .net platform (all of them).
After many searches on the web, trying some tutorials about maven, tomcat, eclipse I can't reach any way to debug apiman correctly. I can debug some calls on rest-impl.

When I add a server (wildfly or tomcat) and start debugging with eclipse the apiman was not get up, but it deployed when I try with remote java application it works, but only attaching to the external running server and without deploying from eclipse or IntelliJ. 

I tried this https://planet.jboss.org/post/setting_up_your_apiman_development_environment, but DevServer class was removed and this http://www.apiman.io/latest/developer-guide/apiman-developer-guide.pdf and not get it running 'seamless'

Having said all that, my question is:

Is there any documentation like that https://apicurio-studio.readme.io/docs/setting-up-a-development-environment for apiman?

PS: I'm sorry about a noob question like that =(

**Comment by volkflo** [comment]
Hey @tevosouza,

I don't have any tutorial but I can explain how we achieve this.
We are running apiman with docker. We have a container for the UI+Rest and one for the vertx gateway.  On our local development devices, we start the containers always with the debug flags that are needed to attach a remote debugger.

So we also don't have a direct run and debug command within Intellij. 

But I remembered that we did this in the past, but switched then somewhen to the direct docker way because this fits our needs.
Below you can find the configuration of Intellij for running apiman in debugging mode. You can simply add a run command before to build the whole project.
Unfortunately, the tomcat integration is only available within Intellij Ultimate. 

![image](https://user-images.githubusercontent.com/13332383/76728598-73276a00-6757-11ea-80c4-a627db74d60c.png)
![image](https://user-images.githubusercontent.com/13332383/76728621-85090d00-6757-11ea-93cb-caa2e983d55b.png)

I hope this helps you a little bit :)

**Comment by EricWittmann** [comment]
There is no documentation like we have in Apicurio (sadly).  However let me look into this a little bit and see what I can remember.  I recall having a quick way to test things out without requiring a full rebuild/deploy cycle.  I think I know what it is. 👍 

But first I'm trying to figure out this /swagger.json thing in Wildfly.

**Comment by EricWittmann** [comment]
OK I'm going to commit a simple shell script that will set up a development server.  And I'll create a Readme.md file in the same location that will explain how to set up a development environment in Eclipse.  The only thing is that it will *not* explain how to set up a development environment for debugging front-end code.  I sadly don't have time ATM to resurrect how to do that with AngularJS. :(

**Comment by EricWittmann** [comment]
Here we go:  https://github.com/apiman/apiman/blob/master/tools/devenv/Readme.md

**Comment by tevosouza** [comment]
Thanks a lot! 
It's alive!!!

Finally, I get it working!

@EricWittmann very nice the 'how to'  and @volkflo  thank you for showing you setup
It worked like a charm for API debugging!

I'm getting forbidden error (403) when trying to access UI from war deploy, but no problem because I run it using gulp for tests and development purposes.

**Comment by tevosouza** [comment]
I'll start to work on #812 issue ;)
thanks again!
