### ISSUE TITLE
Apiman to Keycloak Identity Brokering

### ISSUE THREAD

**Issue by mark-kumoco** [apiman/apiman#864]
Hi,
Im not sure if this is an 'issue', but I'm also not sure where else to post the question. Pls let me know if there is somewhere more suitable?

I am testing using Apiman with Auth0.com (initially just OpenIDConnect but eventually also with Authorisation). If I create a JWT policy on an API endpoint in Apiman pointing to my Auth0 domain using the "URL to a JWK(S)" and "Key ID (kid) of JWK(S)" and then POST a request with Postman to Apiman using the encoded access token from Auth0, I get authenticated ok on the endpoint with this JWT policy. So far so good. But this isn't identity brokering, is it? I mean KeyCloak hasn't been configured with anything pointing to Auth0 and this is just Apiman using Auth0 for direct authentication, right? 

Mark

**Comment by volkflo** [comment]
Hi @mark-kumoco,

I think this is rather a question than an issue but I think Github is still fine for this :)
As I am the one who implemented the JWK(S) support via URL, I can say that this has nothing to do with identity brokering and keycloak. The idea behind this was "just" to validate a token from and JWK instead of a fixed signing key. Auth0 allows you to rotate signing keys automatically and this feature prevents you from always changing the signing key.

The policy is completely independent from keycloak because it only validates the tokens.

If you want to use keycloak as your identity broker I recommend to read the official keycloak documentation: https://www.keycloak.org/docs/latest/server_admin/index.html#_identity_broker

And then you could use the keycloak oauth policy or configure the JWT Policy to the JWK(S) Url from keycloak.

Hope this will help you a little :)

**Comment by mark-kumoco** [comment]
Yes, that helps me move forward! Thanks.

**Comment by mark-kumoco** [comment]
Hi volkflo,
I've followed the instructions on the link  above on creating an OIDC identity provider for Auth0 and also swapped the "JWT Policy" on Apiman to a "Keycloak OAuth Policy" pointing towards the local Keycloak (I am using an Apiman container from dockerhub - apiman/on-wildfly11) and now when I send to the endpoint from Postman I get an "Invalid token signature" 401 error. The JWT Policy has the "access_token" forwarded via "Forward Keycloak Token Information" and I have enabled/disabled the "Validate Signatures"/"JWKS URL" in Keycloak but neither make a difference. I've also generated a new Auth0 access token, but still the same 401 error. The Auth0 client_id and client_secret in Keycloak are the same as those that are used to create the access token.

I also had a look at "Authentication" in Keycloak and under "Client" flows, I have the default of "Client Id And Secret" and "Signed Jwt" with "Alternative" selected.

Did I miss something?

Mark

**Comment by volkflo** [comment]
Hi Mark,

is it possible that you can post some of your configurations?
Otherwise, it is hard to guess what is going on here.

But I think you have to get the token from keycloak as keycloak is now the provider instead of Auth0. And then the token is signed by keycloak. I am sorry if I misunderstood something.

Regards,
Florian

**Comment by mark-kumoco** [comment]
Thanks Florian. I think it was me who was misunderstanding something :) thanks for your help! Mark
