### ISSUE TITLE
Question: Apiman Policy with HTTP Method and Oauth claim

### ISSUE THREAD

**Issue by mark-kumoco** [apiman/apiman#868]
Hi,
Is it possible to create a policy, similar to an Authorization Policy, that limits access to a specific HTTP Method but via Apiman looking at an Oauth claim? From what I can see only "groups" are available in Authorization Policies. I have tested using groups with Keycloak and indeed the policies work as expected, but I need to test Apiman with Auth0 JWTs and claims similar to:
read = GET
write = POST + GET
full = POST + GET + DELETE
Is it possible to filter HTTP method access via another existing type of policy? Or can this be done via a custom type of Apiman policy?
Mark

**Comment by volkflo** [comment]
Hi @mark-kumoco,

I think your case is not possible with the existing policies at the moment.
You could use keycloak roles to protect your HTTP methods.
Then you would configure the two policies behind each other:

1. Keycloak OAuth
![image](https://user-images.githubusercontent.com/13332383/87510074-299e4b80-c673-11ea-9a2c-716a06e99f0e.png)
2. Authorization
![image](https://user-images.githubusercontent.com/13332383/87510100-39b62b00-c673-11ea-834e-22372035fcda.png)

Otherwise, you may implement your own policy or maybe add a switch to the JWT/Keycloak policy to forward the claims to the Authorization Policy, the same as the Keycloak OAuth Policy does this with roles. At the moment you can only configure to forward claims as headers.

Hope this helps you a little bit :)

Regards,
Florian

**Comment by mark-kumoco** [comment]
Yes it helps. Thanks Florian.
