### ISSUE TITLE
No roles have been extracted during authentication

### ISSUE THREAD

**Issue by nishasumesh** [apiman/apiman#876]
Hi,

I have created an organization-roles - client app - apis. (Have assigned members to my organization and created api's and apps using that member login). I tried adding basic autherization policy with static username and password. that also worked fine. 

But when I added authorization policy (for the logged in user cohere_user), i am getting error. 
{
    "type": "Other",
    "failureCode": 10010,
    "responseCode": 0,
    "message": "No roles have been extracted during authentication.  Make sure the authorization policy comes *after* a compatible authentication policy in your configuration.",
    "headers": {}
}

![Screenshot 2020-07-30 at 7 08 32 PM](https://user-images.githubusercontent.com/25498796/88929765-32f4fe00-d298-11ea-92f4-2aea4d61fe21.png)
![Screenshot 2020-07-30 at 7 09 09 PM](https://user-images.githubusercontent.com/25498796/88929771-35575800-d298-11ea-8adb-6f66afec78e2.png)

Is there anything I am missing.

**Comment by volkflo** [comment]
I think this is a configuration problem because the role is not equal to the username:
![image](https://user-images.githubusercontent.com/13332383/89012624-c3702480-d312-11ea-91a0-2e15093b4c9d.png)
To use this feature you need another policy before you Authorization Policy like the Keycloak OAuth Policy and set "Forward realm roles" to `true`:
![image](https://user-images.githubusercontent.com/13332383/89012825-18139f80-d313-11ea-82da-426caa660b64.png)

**Comment by EricWittmann** [comment]
@volkflo is exactly right.  For the Authorization policy to work, you first need a policy of some sort to actually extract roles from the authenticated user.  I can't recall if the BASIC auth policy can do this - it might be able to do it via a RDBMS query.  The Keycloak auth policy can definitely do it, because Keycloak responds with a JWT token and the user roles get extracted from that.  

But in any case, those roles must be extracted by **something** before the Authorization Policy will be able to use them to make decisions.

**Comment by nishasumesh** [comment]
ok I will check that.

**Comment by volkflo** [comment]
I will close this due to inactivity. If there are further questions please open a new issue.
