### ISSUE TITLE
Authorize path without requiring a role

### ISSUE THREAD

**Issue by ncasaux** [apiman/apiman#921]
Hello!

I would like to authorize a subpart of my api to a clientApp. 
So far, the only way I found was to use a a basic auth policy (for example) and an authorization policy.

My issue is that I would like to have the same functionality, but without requiring a role (hence no LDAP or database for the basic auth policy).

Is this something which can be achieved ?

Thanks in advance!

**Comment by EricWittmann** [comment]
Do you want the user to still have to authenticate?

I think it sounds like what you want is an **Authentication** policy that only applies to certain parts of your API and not others.  Meaning you can access `/api/foo` without providing credentials (open) but if you access `/api/bar` then you need to provide valid credentials.  Is that it?

**Comment by ncasaux** [comment]
Hello Eric,

Actually, I don't need the user to authenticate, the apiKey is enough in my usecase.

Let's imagine I have a large API with `/vehicles/boats` and `/vehicles/cars`.
I don't want the allow the clients to access to all the sub parts of the API.
- I would like to allow only `/vehicles/cars` to a specific clientApp1
- I would like to allow only `/vehicles/boats` to another specific clientApp2
- I would like to allow both `/vehicles/boats` and `/vehicles/cars` to another specific clientApp3

How could I achieve this ?

I hope my explanations are clear ! :)

**Comment by EricWittmann** [comment]
Yes I think that's clear.  There is an Apiman plugin that I think almost does what you want:

https://github.com/apiman/apiman-plugins/tree/master/url-whitelist-policy

Have a look at that and see if it solves your use-case.

I think it's close, but I'm not sure it quite solves the problem, since I'm not sure how you expect to map the clientId to the set of allowed endpoints.  Can you explain how you see that mapping work?  What I mean is this:  how does the gateway/policy know that clientApp3 can access both endpoints while clientApp1 can only access cars?

If you use the URL Whitelist Policy you could configure it as a Client App Policy differently for each client.  But that requires cooperation with the client app developers...

**Comment by ncasaux** [comment]
Well, this plug-in seems to be exactly what I need !
I don't know why I didn't find this it earlier...
Thank you Eric!
