### ISSUE TITLE
Maven artifacts for version 1.5.7.Final?

### ISSUE THREAD

**Issue by james-bostock** [apiman/apiman#927]
Hi,

The Maven central repository does not have artifacts for Apiman version 1.5.7.Final. Are there plans to publish these artifacts (and, for completeness, those for version 1.5.6.Final)?

Thanks

**Comment by volkflo** [comment]
@EricWittmann Do you have an idea why the artificats are missing?
1.5.5 is fine and 2.0.0 is also available:
![image](https://user-images.githubusercontent.com/13332383/97865002-c7448600-1d09-11eb-85d0-33a7d65b3a74.png)

**Comment by EricWittmann** [comment]
Yeah there were some issues with the release scripts for some of the versions.  It would be possible to correct.  I guess we need to fix two things:

1. Missing "releases" in GitHub
2. Missing artifacts in maven central

The missing releases is easy enough to fix via the GitHub UI I think.

The maven central artifacts are slightly harder and require some tweaking of the root `pom.xml` so that the sonatype release plugin works.

**Comment by EricWittmann** [comment]
My mistake - it looks like the apiman releases already exist (as expected) and it's only the maven central artifacts that are missing.

**Comment by EricWittmann** [comment]
Deploy to maven central in progress for version `1.5.7.Final`

**Comment by EricWittmann** [comment]
OK the artifacts for `1.5.7.Final` are pushed to maven central.  I'm pushing `1.5.6.Final` for completeness (as suggested).  But closing this now since it's technically already done.  :)
