### ISSUE TITLE
Unable to access http://localhost:8080/apiman/developers

### ISSUE THREAD

**Issue by phenompavan** [apiman/apiman#928]
Hi,

I've setup apiman and everything looks okay. When I launched developer portal I'm unable to see developers as API failed(404 status code) with response
`RESTEASY003210: Could not find resource for full path:http://localhost:8080/apiman/developers.`

I can see in the code that in manager/api/rest/src/main/java/io/apiman/manager/api/rest/IDeveloperResource.java it's mentioned as 

`@Path("/developers")`
while for all other APIs the slash is not there ex: 

`@Path("gateways") and @Path("plugins")`
Not sure if this is an issue. How do I fix it? Please let me know as this is a blocker for me.

I'm using 2.0.0.Final version

I tried to build the project by changing /developers to developers, but I'm getting following error on running mvn clean install (Java Version: 12.0.1, Maven Version: 3.6.3) 

 
![image](https://user-images.githubusercontent.com/73810156/98138408-1399ec80-1ee9-11eb-921b-606bb84f9b0c.png)

**Comment by EricWittmann** [comment]
Thank you @phenompavan for moving this issue here.  @volkflo and @bekihm can you guys comment on this?

**Comment by bekihm** [comment]
@phenompavan you mentioned that you are using the 2.0.0.Final version. The developer portal backend is not included yet in this version. It comes with version 2.1.0 of the apiman project which is the current master of the project.
Sounds like in this issue here:
https://github.com/apiman/apiman-developer-portal/issues/9#issuecomment-716387854

Did you try the current master branch of the apiman project with the apiman-developer-portal version 2.1.0 (current main branch)?

> I tried to build the project by changing /developers to developers, but I'm getting following error on running mvn clean install (Java Version: 12.0.1, Maven Version: 3.6.3)
So you tried to execute the current master branch of apiman instead of the release and it does not work out?

**Comment by phenompavan** [comment]
Hi @bekihm I installed 2.0.0.Final using docker where the developers API issue there. Then I thought of debugging and was setting up this API in my local using master branch where I faced the build error when I ran `mvn clean install`

**Comment by bekihm** [comment]
Ah, I looked it up the apiman project is limited to java 8 can you try this version?
See here similar issue like yours: https://github.com/apiman/apiman/issues/793

We have already an issue to support a newer java version:
https://github.com/apiman/apiman/issues/796

**Comment by phenompavan** [comment]
I'll try that. When can we expect 2.1.0 release? And also Java newer version support please?

Also, can you give me the steps to build a docker image of this project please?

**Comment by volkflo** [comment]
@phenompavan A new release can take a while because we need new GitHub actions to also release the developer portal.
But we try to create more up to date "latest" images on docker hub that represents the master branch.

The docker images can be built with `mvn clean package docker:build -P docker -DskipTests` .

We are always looking for help, if you want to support us, we are happy to receive some contributions :)

**Comment by volkflo** [comment]
@phenompavan You can try again with `docker pull apiman/on-wildfly:latest`. `latest` will now always be updated if something is merged into the master branch of apiman.

**Comment by volkflo** [comment]
Apiman 3.x will contain a new developer portal with a different deployment strategy. So I will close this.
